### ISSUE TITLE
Unable to import TypeScript types from another file 

### ISSUE THREAD

**Issue by sasial-dev** [pipe01/esbuild-plugin-vue3#25]
I'm trying to import TypeScript types from another file, yet I get this error:

```
✘ [ERROR] [@vue/compiler-sfc] No fs option provided to `compileScript` in non-Node environment. File system access is required for resolving imported types.

src/app.vue
12 |  import { Settings } from './settings';
13 |  
14 |  const props = defineProps<Settings>()
   |                            ^^^^^^^^
15 |  const emit = defineEmits<{ updateTimetable: [] }>()
16 |  </script> [plugin vue]

    src/view.ts:5:16:
      5 │ import App from './app.vue';
        ╵                 ~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/esbuild-plugin-vue3/dist/index.js:218:34:
      218 │                             build.onLoad({ filter: /\.vue$/ }, function (args) { return cache.get([args.path, args.namespace], function () { return __awaiter(_this, void 0, void 0, function () {
          ╵                                   ~~~~~~

    at /Users/***/node_modules/esbuild-plugin-vue3/dist/index.js:218:35
    at step (/Users/***/node_modules/esbuild-plugin-vue3/dist/index.js:67:23)
    at Object.next (/Users/***/node_modules/esbuild-plugin-vue3/dist/index.js:48:53)
    at fulfilled (/Users/***/node_modules/esbuild-plugin-vue3/dist/index.js:39:58)
```

**Comment by pipe01** [comment]
Thank you, should be fixed in next release.

**Comment by sasial-dev** [comment]
Thank you!
